name: world_tool_projects
description: A package for working with World Tool Project files
version: 1.1.2
repository: "https://github.com/zimlit/world-tool-projects"

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {xml: ^6.1.0}
